name: Docker Image CI

on:
  push:
    tags: [ "*" ]
      workflow_dispatch:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_REPOSITORY }}:$(date +%s)
